version: '3.8'

services:
  guineeticket-frontend:
    build:
      context: ./guineeticket-frontend
    ports:
      - "3001:80"
    container_name: guineeticket-frontend
    platform: linux/amd64
    restart: unless-stopped

  guineeticket-backoffice:
    build:
      context: ./guineeticket-backoffice
    ports:
      - "9080:80"
    container_name: guineeticket-backoffice
    platform: linux/amd64
    restart: unless-stopped

  guineeticket-backend-api:
    build:
      context: ./guineeticket-backend-api
    ports:
      - "80:80"
    container_name: guineeticket-backend-api
    platform: linux/amd64
    depends_on:
      - db
    restart: always
    env_file: 
      - .env
    environment:
      - DB_HOST=db            # Ajoutez cette ligne pour définir l'hôte DB
      - DB_PORT=3306          # Assurez-vous que le port MySQL est le bon

  db:
    image: mysql:8.0
    container_name: mysql-container
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
      - ./eticket_db.sql:/docker-entrypoint-initdb.d/eticket_db.sql
      - ./db/init-scripts/create_user.sql:/docker-entrypoint-initdb.d/create_user.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    platform: linux/amd64
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=${DB_USER}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - db

volumes:
  db_data:
